FROM node:20-alpine
WORKDIR /app
COPY apps/server/package*.json ./
RUN npm ci
COPY apps/server/ .
COPY apps/server/prisma ./prisma
RUN npx prisma generate
RUN npm run build
EXPOSE 4000
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/index.js"]
