[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	tzapu/WiFiManager @ ^2.0.15-rc.1
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^6.21.3
	mandulaj/PZEM-004T-v30 @ ^1.1.2

build_flags = 
	-D METER_ID=\"PG001\"
	-D MQTT_BROKER=\"192.168.1.100\"
	-D MQTT_PORT=1883
